name: swinswap
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - ipykernel
  - ipython
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - pip
  - python=3.9
  - python-dateutil
  - python_abi
  - pytorch=1.11.0
  - torchaudio
  - torchvision
  - pip:
    - accelerate
    - cachetools
    - charset-normalizer
    - click
    - cycler
    - cython
    - google-auth
    - google-auth-oauthlib
    - google-pasta
    - grpcio
    - huggingface-hub
    - jupyter
    - jupyter-console
    - jupyterlab-pygments
    - jupyterlab-widgets
    - keras
    - keras-preprocessing
    - matplotlib
    - mistune
    - moviepy
    - mtcnn
    - notebook
    - numpy
    - opencv-python
    - opencv-python-headless
    - pandas
    - regex
    - requests-oauthlib
    - rsa
    - sacremoses
    - scikit-image
    - scikit-learn
    - scipy
    - send2trash
    - tensorboard
    - timm
    - tokenizers
    - tqdm
    - transformers
    - wandb